services:
  sample:
    build: ./
    tty: true
    stdin_open: true
    volumes:
      - type: bind
        source: "../"
        target: "/work"
    networks:
      - ollama

networks:
  ollama:
    external: true
